.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "GIT\-SQWISH" "1" "September 2013" "" ""
.
.SH "NAME"
\fBgit\-sqwish\fR \- Squash changes in a branch
.
.SH "SYNOPSIS"
\fBgit\-sqwish\fR <master\-branch> [<commit\-message>]
.
.SH "DESCRIPTION"
Take all commits in a branch, compress them into \fIone\fR commit on top of the \fBmaster\-branch\fR, apply to \fB$CURRENT_BRANCH\.sqwished\fR branch\.
.
.SH "OPTIONS"
<master\-branch>
.
.P
Branch to squash commits on top of\.
.
.P
<commit\-message>
.
.P
If commit\-message is given, commit will be executed automatically and message will be prepended to the default summary (all commit summaries of sqwished commits)\.
.
.SH "EXAMPLES"
.
.nf

$ git sqwish master
[dev/my\.feature\.sqwished 97b70be] Added abc\. Added def\.
 0 files changed
 create mode 100644 abc
 create mode 100644 def
.
.fi
.
.SH "AUTHOR"
Written by Todd Wolfson <\fItodd@twolfson\.com\fR>
.
.SH "REPORTING BUGS"
<\fIhttps://github\.com/twolfson/git\-sqwish/issues\fR>
.
.SH "SEE ALSO"
<\fIhttps://github\.com/twolfson/git\-sqwish\fR>
